### ISSUE TITLE
Video Check : Audio Zero

### ISSUE THREAD

**Issue by iamkimkelvin** [Palakis/obs-ndi#117]
my streaming setup doesn't receive the sound from my gaming pc
using both 4.2.2 ndi and obs 21.0.1
reinstalled both still no luck
on newtek's monitor there's audio and video
on obs only video no audio

![36301995-b88c4a90-1356-11e8-9cab-7bd5fdf9c063](https://user-images.githubusercontent.com/36532314/36308242-aa939754-136f-11e8-83e2-32eb46ecaae9.png)

**Comment by TheWookieWay** [comment]
if i remember correctly, if you have multiple sources for audio on the gaming pc, only the FIRST one will transmit across NDI
And, to avoid a monitoring sound bug, you had to set monitoring on the streaming pc to an unused device like a monitor HDMI or something, but I think that bug might be fixed.

I can't check for sure, because my streaming Pc needs a new fan, but I think this will help you solve your problem.  Perhaps someone else can post a more accurate response.

**Comment by Palakis** [comment]
@TheWookieWay 
> if i remember correctly, if you have multiple sources for audio on the gaming pc, only the FIRST one will transmit across NDI

Absolutely not. On the main output it sends the whole program audio, not just one source. Otherwise it would be a bug.
