### ISSUE TITLE
In the Wifi funcina and in the cable lan not

### ISSUE THREAD

**Issue by joaocarlosmaia** [Palakis/obs-ndi#121]
I have a problem, when I activate the wifi the pc 2 (stream) captures the image of the normal pc 1 (gamer) but when I disable the wifi and I connect the cable that is in the same router, pc 2 can not capture the pc1 image and a red dot is left on the top left.
OBS 21.0.1
OBS NDI 4.2.2

I've already disabled the firewall.

**Comment by Helgaiden** [comment]
still sounds firewall related, whether that be in windows, an anti-virus, or directly in the router. Do more digging on where you can add exceptions for OBS

**Comment by Palakis** [comment]
General networking tips with NDI:
- Use Gigabit Ethernet
- Use a proper switch, either managed or unmanaged, instead of the built-in Ethernet ports of your home router. They work like a traditional switch, but sometimes processing is done on the router's CPU instead of on a dedicated processor.
- On Windows
  - **Don't ever use the Public profile on the network adapter used for NDI.** This interferes with source discovery.
  - Add a firewall exception for OBS Studio in your firewall
- Reset your TCP settings after installing the NDI runtime, as the installer provided by NewTek silently enable Compound TCP which reduces available bandwidth.

If you still encounter issues, please open a new issue here on this tracker.
