### ISSUE TITLE
Build error: SPEAKERS_QUAD deprecated?

### ISSUE THREAD

**Issue by h1z1** [Palakis/obs-ndi#122]
Hi,

Not sure if this was just two branches out of sync but it appears  https://github.com/jp9000/obs-studio/commit/fb580535c944fa2845d157814b1636de0831056d broke obs-ndi as it replaces SPEAKERS_QUAD (https://github.com/Palakis/obs-ndi/commit/0308bdbb3c03b48afd16b4c007f17727c39e8753) with SPEAKERS_4POINT0

This was corrected with https://github.com/Palakis/obs-ndi/commit/91082fb2517606f3392732cf1357754c14c1bcf0  but reverted in https://github.com/Palakis/obs-ndi/commit/c003b11e32eafbfc4bacdb78899ac7554ae766a1  with no obvious reason?

**Comment by Palakis** [comment]
`SPEAKERS_4POINT0` isn't available before version 21.0.0 of the OBS API. It was changed so it could compile in my local dev environment, but this change has been reverted, as it was breaking CI builds (which compile against a stable release of OBS Studio).

This has been fixed with the release of OBS Studio 21.0.0. The following piece code ensures backwards compatibility when compiling: https://github.com/Palakis/obs-ndi/blob/master/src/obs-ndi-source.cpp#L180-L184
