### ISSUE TITLE
obs-ndi

### ISSUE THREAD

**Issue by mkspikey** [Palakis/obs-ndi#149]
So i have a black screen in my streaming pc, im connected via wifi changed the wifi settings to private and i recieve a sound aswell now :)
my highest res in ym streaming pc is much lower then my gaming pc maybe that cuases the issue?
when i press twice on the ondi source in my streaming pc i see my streaming pc setup but the canvas is still black...
Streaming pc - amd a9 3.0 ghz
gaming pc - asus rog astrix

**Comment by Palakis** [comment]
Don't every use wifi for NDI. It's too unreliable.

General networking tips with NDI:
- Use Gigabit Ethernet
- Use a proper switch, either managed or unmanaged, instead of the built-in Ethernet ports of your home router. They work like a traditional switch, but sometimes processing is done on the router's CPU instead of on a dedicated processor.
- On Windows
  - **Don't ever use the Public profile on the network adapter used for NDI.** This interferes with source discovery.
  - Add a firewall exception for OBS Studio in your firewall
- Reset your TCP settings after installing the NDI runtime, as the installer provided by NewTek silently enable Compound TCP which reduces available bandwidth.
