### ISSUE TITLE
NDI source connected, but is not capturing anything

### ISSUE THREAD

**Issue by Chrisg69** [Palakis/obs-ndi#150]
My Streaming PC connects to my gaming laptop through obs NDI just fine. But it will not pick up any sound or video. This happens every now and then and somehow fixes itself eventually, but is there any known cause to this? Thanks a ton to anyone has any advice for me!

**Comment by Helgaiden** [comment]
most of the time this is down to firewall. Either the windows firewall or any anti-virus/internet security suite you might have installed. Make sure to fully allow OBS in any/all firewalls you have.

**Comment by kevingarman** [comment]
Same problem here.  I'm running OBS 21.1.1 on Linux with version 4.4 of this plugin.  I can browse sources, but when I pick one nothing happens...I just get a black screen.

**Comment by kevingarman** [comment]
Note...I've seen the same thing on a Mac, but I open an NDI monitor app, then I receive the stream both in the monitor app and OBS.

**Comment by Palakis** [comment]
General networking tips with NDI:
- Use Gigabit Ethernet
- Use a proper switch, either managed or unmanaged, instead of the built-in Ethernet ports of your home router. They work like a traditional switch, but sometimes processing is done on the router's CPU instead of on a dedicated processor.
- On Windows
  - **Don't ever use the Public profile on the network adapter used for NDI.** This interferes with source discovery.
  - Add a firewall exception for OBS Studio in your firewall
- Reset your TCP settings after installing the NDI runtime, as the installer provided by NewTek silently enable Compound TCP which reduces available bandwidth.

If you still encounter issues, please open a new issue here on this tracker.
