### ISSUE TITLE
NDI | Source name showing up, black screen when selected.

### ISSUE THREAD

**Issue by levmtt** [Palakis/obs-ndi#163]
Been trying to set this up for a while, and keep facing the same issue. I am using NDI Scan Converter on my Gaming PC, and on my streaming pc I am using the plugin and have installed NDI Tools

I have now tested it on my streaming pc, in the studio monitor, it captures everything, but when I select my gaming pc it detects nothing. Even on my gaming pc, it's own desktop isn't captured

**Comment by cooljacob204** [comment]
I had the same issue, turned out it was a firewall issue. I resolved by disabling the firewall on both computers. Careful about doing this if you are on a public network.

**Comment by golgoo13** [comment]
Oh thanks you ! cooljacob204 for me it's good i have lag

**Comment by teckn07** [comment]
Windows 10 host, Windows Server 2016 capture I had the same issue what I did instead of turning off fire wall like on the windows firewall and then the open the turn firewall on or off instead of turn it off click the check box thats says notify me when an app is block by the firewall. I did that when I started obs it popup and allowed me to use NDI source.
