### ISSUE TITLE
Build for Raspberry Pi?

### ISSUE THREAD

**Issue by JonnyTech** [Palakis/obs-ndi#191]
Are there any prebuilt binaries or instructions to build `obs-ndi` for Raspberry Pi?

**Comment by ElectronicWar** [comment]
OBS itself does not work on any ARM platform, so ARM build instructions for this plugins make no sense.

**Comment by JonnyTech** [comment]
Ah, that explains it. Thanks. Trying ffmprg but performance is poor.

**Comment by prathamesh-gharat** [comment]
I am running OBS on a Raspberry PI 4 now. Streaming directly from a raspberry PI has poor performance. Was thinking OBS-NDI would help with that so that I can output an NDI stream (assumption it takes less CPU) to my PC over the local network and then stream from my local PC. I am assuming this would allow me to stream with a better resolution/framerate than streaming directly from the RPi.

**Comment by ElectronicWar** [comment]
Using NDI together with OBS will not really help performance-wise.
While NDI is rather light, it's still a CPU-based video codec.

The Pi has a bigger issue with GPU performance running OBS (low OpenGL performance). You're most likely better off using NDI without OBS or by using ffmpeg to create a light-weight stream, possibly by utilizing the OMX hardware encoder of the Pi.
