### ISSUE TITLE
My Game Lags When Using NDI 

### ISSUE THREAD

**Issue by WhyIsItAlwaysMe** [Palakis/obs-ndi#201]
I am using an RX 580, 16GB RAM, Ryzen 7 1700.

I am trying to use the OBS plugin called NDI but every time I enable it, my game lags really bad. I don't know why this happens but I'm looking at my GPU/CPU on the task manager and Its only using like 10% . My upload speed is 20mb and download is 200mb not sure if thats of any use but I want to be able to record/stream using NDI

**Comment by CoDEmanX** [comment]
@WhyIsItAlwaysMe Does the game lag for you while playing, or does it only lag in the video stream?

What version of obs-ndi do you use? I saw a streamer yesterday who had updated to NDI 4.5.0 but the stream stuttered like running between 15-30 fps instead of the previous 60 fps. He reverted to the previous version and it worked fine again.

@Palakis As per the release notes, the networking changed (improved) because of the upgrade to NDI 3.5. Are you aware of any regressions? I can get you in contact with the streamer who had issues with the latest version if you want.

**Comment by WhyIsItAlwaysMe** [comment]
Yes, It lags when playing, but does not lag in video stream. I get huge stuttering when getting shot. I am not sure which one I am using but today, I reformatted my PC and tried a different route. I only downloaded NDI tool 3.6 on my PC and used scan converter and it still lags. regardless.

I just check and I am indeed running 3.6 on both of the system. And I do appreciate your offer for me to contact this streamer but unfortunately we have different issues as he has a lag in his stream and my game just lags while NDI is turned on. I'm certain I used 3.5 before and still had the problems.

Thank you for your response

**Comment by Helgaiden** [comment]
Go through all your sources, especially browser sources, and check the box that says to disable the source when it is not showing/active. Make sure that your OBS video settings on the streaming PC have the base canvas, "output (scaled) resolution" and "common fps value" mirroring the "output (scaled) resolution" and "common fps value" of the same section on the gaming PC. Make sure you arent clicking "start streaming" on the gaming PC, and make sure your OBS is up to date.
