### ISSUE TITLE
Streaming laptop not detecting NDI input from gaming desktop

### ISSUE THREAD

**Issue by KomradeIvan** [Palakis/obs-ndi#205]
Hello all,

I use NDI to send footage from my gaming desktop to my streaming laptop via a usb dongle, crossover cable and network bridge. 

I recently moved into my university apartment and NDI has not worked since then. When I try to add an NDI input on my laptop, the drop-down menu does not open to show input options. Before I moved in, I was able to stream without any issues. I have tried to reset the network bridge, allow OBS through firewalls on both computers, and reinstalling network adapters. No success. Please help.

Gaming Desktop Specs:

- Intel i7-7700K
- EVGA GTX 1060 6GB vram
- 16GB DDR4 ram
- 120GB SSD
- 1TB HDD

Streaming Laptop Specs:

- Intel i7-4710HQ
- GTX 965M
- 8GB DDR3 ram
- 750GB HDD

**Comment by Helgaiden** [comment]
Get yourself a little 4 port gigabit ethernet switch. Take the apartment's ethernet plug and run a cable into the switch, then plug both the laptop and desktop into the switch. See if that helps.

**Comment by KomradeIvan** [comment]
@Helgaiden The WAP in my unit has available ports that I could wire my laptop to. Would that work, or does the switch provide something that the WAP doesn't?

**Comment by Helgaiden** [comment]
The switch would provide for both computers to communicate with each other more efficiently (instead of having to travel thru your school apartment network) for NDI to work better, but more importantly it would get around any network ports being blocked on that network preventing NDI from working in the first place. The NDI traffic should go between both computers first thru the switch, then the one PC that is streaming will send it's feed out from the switch into the apartment's network like usual. The switch will also give internet to both computers. They may frown on this device being there, do not let then know you have one if you do this.

**Comment by KomradeIvan** [comment]
@Helgaiden I'll give it a try. Thank you for the explanation!
