### ISSUE TITLE
buffering/bad frame rate on stream

### ISSUE THREAD

**Issue by DryReef** [Palakis/obs-ndi#226]
OBS log:
https://obsproject.com/logs/6qIgRdMRjLEpYo_3

Been getting this frustrating issue the last 5 days... Didnt have issues with these settings for the past few months and all of a sudden now its dropping frames on the stream... frame rate looks completely fine on the gaming pc and on obs preview on streaming pc. 

In case you're curious here's my hardware:

encoding/streaming pc:
i7 8700
16 gigs ram
gtx 1060

Gaming PC
i5 7600k
16 gigs ram
gtx 1080

Both computers connected with cat 7 cables to router/modem. Internet is with Spectrum, speed is 400 mb/s download, 20 mb/s upload

Obs settings on streaming pc
2500 bitrate (tried going as low as 1000 and buffering still happened!! wtf)
cpu preset: placebo or very slow

As i mentioned before, i didnt have any issues with any of this for the past couple months until a few days ago

You can see the buffering issues i been having on my twitch here http://www.twitch.tv/dryreef/v/313971446?sr=a&t=522s

**Comment by zovk** [comment]
on my site is switched. 
on my gaming rig i have bad performance  no real feel 120Hz Smooth and low frames.   my streaming rig  is working well.

**Comment by Notmeagain** [comment]
You should try a different CPU Preset.

The "Slower" you go, the more work the CPU is required to do to encode a frame.
In your logs: "Video stopped, number of skipped frames due to encoding lag: 18537/43711 (42.4%)"

Try setting it to medium, or fast.

If you are able to monitor the streaming pc's OBS interface, you might see "Encoding overloaded".

I've been tweaking my stream PC, after moving from an Nginx+rtmp server to NDI and have settled on "fast" for a 1280x720@60 - 4500kbs stream. If i push it to slow or slower i can guarantee to hit encoding overload.
