### ISSUE TITLE
Losing Frames

### ISSUE THREAD

**Issue by DeathmannX** [Palakis/obs-ndi#243]
Hello Guys,

i got since i use this OBS Plugin a Problem that i don't understand.
If i play and don't have OBS with the NDI Plugin on everything is fine i got 144 FPS without any Problem.

If i start OBS with NDI on and play the same way i still got 144 FPS sometimes maybe a little bit less but that is not the strange part.
Eve if i got 144 FPS i still got the feeling everything is mutch more like motion blur.

This is my PC:
https://www.userbenchmark.com/UserRun/11599410
2x 60 Hz Monitors
1x 144 Hz Monitor

This PC dosen't do stream only via NDI to my Streaming PC and that handles the Streaming Stuff.

Can somebody explain me where this come from?

**Comment by VexMex** [comment]
ok, so now to the relevant bits

On what rate do stream, 60fps? 30fps? 44.87fps?
On what resolution do you play?
what does your cpu say while streaming with ndi? (since for me it has a 20% impact on cpu)
what game do you play? did you try other games?

but one thing: try seperating the cores the game and obs are using, factorio has the problem to interfere with obs/discord and making it loose frames/voice choppy even tho cpu is fine

is your streaming pc good?
what are your streaming settings there?
what ethernet connection do you use?

**Comment by DeathmannX** [comment]
Ok, here you get it. ;)

I stream with 60 FPS 1080p
I play with 1080p and for normal with 144 FPS
OBS with NDI takes ~10% (it  is started with Admin rights btw.)

I got no Discord open (Teamspeak 3 User ;) )

I would say my Streaming PC is good cause it uses the following Hardware:
https://i.gyazo.com/7385fad7fdd7db42a988e56c811516ed.png

Here is a Benchmark Result of the Streaming PC:
https://openbenchmarking.org/result/1811014-KH-X264TEST297

I use on OBS this Settings:

Output:
--------------
Coder: x264
CBR
Bitrate 6000
Keyframes: 2
Preset: medium
Profile: main
Tune: nothing

Video:
----------------
Basis: 1920x1080
Output: 1920x1080
Filter: Lanczos
FPS 60

NDI Source: Bandwith Highest
Sync: Internal
[X] Hardware acceleration
YUV: Partial
YUV Color Space: BT.709

Ethernet Wired Cat 6 with my FRITZ!Box 6490 Cable

I thing that should be it.
Any Idea why i got that Motionblur Effect on my Gaming PC?

**Comment by VexMex** [comment]
i would say try setting the keyframe interval on 0 (auto) since i got a fragmentation/weirdness in it that made the stream quite diffuse, then, since you are using 1080p basis and output, you dont need the lanczos filter since you dont use any scaling.
the preset on medium is ok, but also try if it happens with fast and faster

and i dont know about the admin rights, i never do that so i cant say if its making a difference

the rest looks good, so it might be some other stuff thats having to do with drivers or windows being meh

**Comment by DeathmannX** [comment]
To be clear that strange Motion Thing happens on my Gaming PC and **not on the Streaming PC**.
I cann't turn off from my Gaming PC to my Streaming PC the Scaling Filter in the Video Tab.

**Comment by VexMex** [comment]
ok that might have then nothing to do with ndi? because now this problem just sounds really really strange since ndi is not doing anything with the capture of the game, it just encodes and sends it away. i didnt expect it to be on your gaming pc. is that problem also there without ndi? if not....i really have no clue why

**Comment by DeathmannX** [comment]
Maybe i found the Problem but i'am not 100% shure.
I tryed everything to figure out where this Effect comes from and than i noticed that i try to capture everything with the Monitor Capture instead with the Game Capture.
First tests look better and i will try that while i stream later today.
