### ISSUE TITLE
Poll NDI hosts periodically or on source creation rather than just at startup

### ISSUE THREAD

**Issue by ravenium** [Palakis/obs-ndi#244]
Hello,

We've been using the NDI plugin with success for a few events.  Initially I was going crazy in that NDI hosts weren't being discovered - why in the world?  

With some packet capture (hey, MDNS requests!) I noticed that NDI feeds only seem to poll on OBS startup, so if you already have your master OBS streamer box up you can't see an NDI host that starts up after.  Ideally it would be nice to have NDI poll for hosts upon source creation rather than just at startup.  Optionally, the idea of manually entering an NDI host name would be useful as well if all else fails.

Thanks!

**Comment by Palakis** [comment]
@ravenium 
Hmm weird, source discovery is supposed to be called everytime the source properties window on an NDI source is opened.

> Optionally, the idea of manually entering an NDI host name would be useful as well if all else fails.

Not only you can manually specify NDI hosts for discovery (useful for cross-network NDI without having to route mDNS as well) in the Access Manager tool provided with the NDI Tools, you can also (since a recent release) manually specify a source name in the "NDI Source" field.
