### ISSUE TITLE
NDI obs scaling

### ISSUE THREAD

**Issue by XPZ2k15** [Palakis/obs-ndi#335]
I'm not sure if this is possible, but I'm going to try and give you a detailed problem. I currently play a game that is 1280x960 ( CSGO, I stretch this to fullscreen ), but when I add it to OBS on 1920x1080 resolution. It has black bars as a monitor would. Normally your Nvidia control panel would stretch this if you put scaling to fullscreen. The current NDI Scan Converter Region of Interest doesn't allow you to properly adjust the window outside of the windows monitor ( active region ) I used a third party program to grab the window and force it to a certain size to capture CSGO without any resolution problems. Now Everything works fine. The only problem is I have black bars on OBS. If I try to stretch it..it stretches it with the black bars. Is it possible to stretch it so it wont have black bars?
![example 2](https://user-images.githubusercontent.com/38363692/63646492-8645f000-c6c8-11e9-93a0-e56af06a0707.png)
![example 1](https://user-images.githubusercontent.com/38363692/63646493-8645f000-c6c8-11e9-8176-be71859793ff.png)
![example 3](https://user-images.githubusercontent.com/38363692/63646497-9d84dd80-c6c8-11e9-8108-92e2c9bdeec8.png)

**Comment by sytem** [comment]
You can crop source in OBS before scaling. In mac-version, option+drag border you want to crop.

Nothing NDI related in my opinion.

**Comment by diddydab** [comment]
Hey, I have the same issue same thing. I play on 4:3 stretched, 1280x960, what third party program did you use to grab the window and force it to a certain size to capture CSGO without any resolution problems? A fix for you scaling problem from your gaming PC is to change your nvidia settings from perform scaling on: Display to perform scaling on: GPU, because NDI takes your entire GPU's output. My game plays fine and works on my gaming PC but on the stream the right side and bottom of the game are bugged and stretched out. Thanks for any help!

**Comment by diddydab** [comment]
Also I would suggest cropping the black bars and then stretching to fit screen on stream of just fitting to screen as well.

**Comment by diddydab** [comment]
I figured it out for myself I just cropped my imagine just message on the thread if u need help again!
