### ISSUE TITLE
Obs-ndi throttle internet connection even offstreaming.

### ISSUE THREAD

**Issue by Vveranation** [Palakis/obs-ndi#382]
This happened after your last few updates. I tried everything like roll back to older version of NDI plugin, OBS, Newtek NDI but i can not solve problem when i open ndi source on my gaming pc and catch it on my streaming notebook its eating my internet connection like 100mb/s also stuck at %100 of my network usage. Please help me!

**Comment by franq123** [comment]
resuelto el temo yo tmb estoy igual

**Comment by franq123** [comment]
> Esto sucedió después de tus últimas actualizaciones. Intenté todo, como volver a la versión anterior del plugin NDI, OBS, Newtek NDI, pero no puedo resolver el problema cuando abro la fuente ndi en mi PC para juegos y la capturo en mi computadora portátil, está comiendo mi conexión a Internet como 100mb / s también atascado en% 100 de mi uso de red. ¡Por favor, ayúdame!

lo areglaste !

**Comment by Palakis** [comment]
@Vveranation 100 Mbit/s is normal bandwidth for NDI. It's also not eating bandwidth on your Internet connection, as it's a LAN protocol.

If you're referring to the fact that previous versions of the NDI runtime installer enabled TCP bandwidth throttling, this has been fixed in previous releases of the NDI plugin installer and is not applied anymore in newer versions of the NDI runtime installer.
