### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by Pablo-Barros** [Palakis/obs-ndi#551]
I tried to use this with my RaspberryPi 4 (4 GB RAM) and Ubuntu Mate 64 bit and it's not compatible. It would be nice to have support for this platform, maybe on future releases Raspberry could be a nice performer for this task.

**Comment by tt2468** [comment]
No way a raspberry pi would be able to run obs *and* do any kind of NDI workload. However, there are other platforms like the jetson which are starting to get reasonable performance. For now, this will have to be labeled as low-priority.

**Comment by rjhornsby** [comment]
I’m probably wrong, but I’ve been trying to find a way to get NDI running on a Pi as well. Nothing fancy, just want to send program output to another monitor over the LAN, using Pi as an NDI-> HDMI bridge. Pi4 is hardware capable of at least this. Right or wrong, NewTek’s apparent position is frustrating because NDI seems to hold a ton of potential.

Sienna has said of NDI “RaspberryPi coming soon” for a long time. NewTek won’t(?) opensource the library to make it possible for anyone else to compile it for ARM. It’s hard to tell exactly what’s going on, but NewTek seems to have maybe been playing some shady games enough to get both ffmpeg and VLC angry with them. Can’t find details, but long ffmpeg threads reference NewTek lawsuit threats toward some OSS projects? All that makes it harder to port, and the OSS community understandably more reluctant to work with them.

It’s not all bad news - Dicaffeine has promise. I had a hard time getting that running - the UI was crazy lagged. Also seems to be closed source. VideoLAN of VLC fame has a project trying to build an OSS NDI library from scratch. https://code.videolan.org/jbk/libndi. Might be something useful there.

**Comment by rjhornsby** [comment]
Quick follow up - the videolan ndi library compiles fine on Raspi hardware, and the included demo ndi binary runs fine. AFAICT, it doesn’t actually do anything with the frames except spit out “got (audio or video) frame” but that seems like a great start. While I can more or less read the library code, I haven’t the first clue how to turn that into usable a video frame. This repo is probably a good companion to see how it’s done.

**Comment by Lizzit** [comment]
Sorrry but I still don't understand... there is or not an NDI for Raspberry??

**Comment by jcoutch** [comment]
The NDI 5 Advanced SDK is out now...which supports encoding/decoding on ARM hardware:
https://www.ndi.tv/sdk/

Would be awesome if support was added to obs-ndi!

**Comment by tt2468** [comment]
Will be implemented: https://github.com/Palakis/obs-ndi/issues/675#issuecomment-968255651
