### ISSUE TITLE
2 PC's: can't find source in one of them

### ISSUE THREAD

**Issue by andresonny** [Palakis/obs-ndi#58]
Hello there,

I've got PC1 (gaming PC) and PC2 (PC for streaming).
I've already installed OBS studio and ndi-plugin on both.
Both enabled NDI Output.
The thing is: I can find PC2 in sources from PC1 but (when I'm at PC2) I can't find the PC1 in sources.
They are connected to the same wifi router and both PCs brand new just installed windows 10-64bits.

I appreciate if someone helps me.

Thanks!

**Comment by SPIKEYPUP** [comment]
I can't say for sure as I just started using this myself, but I would think by design that this would not be allowed as you could cause a circular loop and either which way it would gobble up your NIC/CPU in an instant and make everything choppy if even legible.  Of course I could be wrong, this isn't my software and I just started using it myself, but it works wonderfully and is simple.  Test to see if you enable it only on one at a time that you can see it in both places, again with only ONE PC set as output enabled at a time.  If so, then I'd say everything is working as it should.  I mean for me, I'm using OBS to stream from two PC's, basically using one to Transcode to twitch (5Mbps) and the other to send to Restream(12Mbps) which forwards on to 4 other platforms.  

The NDI output from my gaming PC to the Transcode PC is 280-335Mbps Average (Using 1080P 60FPS), if you are trying to do this over Wi-Fi, with those kind of numbers you'd saturate almost any good-great Wi-Fi router, especially if both were trying to TX/RX at the same time, because remember your 250Mbps output from one, is 250 Mbps input on another PC, for 500Mbps total throughput against the router, over Wi-Fi that is really pushing the limits, if you were to try to RX/TX both at the same time, i.e. Both Output NDI at once, and Both trying to receive, you'd be pushing 1000Mbps, PLUS Overhead of about 25-40Mbps at least.

So I'm thinking this is by design if not prohibited in theory due to buffers etc.  Of course I could be wrong, hopefully one of the devs will get back to you on this soon...  Cheers and best of luck!  :)

Spikeypup

**Comment by Helgaiden** [comment]
Add OBS exceptions in windows firewall, or turn the firewall off to test (on both PCs). Make sure both network cards are gigabit capable (10/100/1000) and that the switch/router BOTH computers are wired into is also gigabit on the ports. This would put you in the optimal situation for getting the plugin working right.

**Comment by pedraodeus** [comment]
hi there, i have the same problem.
gaming pc and streaming pc (notebook)
both with:
ndi, obs last version.
firewall off/on
network cards are gigabit capable
router wired CAT5E
windows 10 brand new installed.
ip automatic
same gateway..

already tested everything... dont know what to do anymore.. =//

anyone have suggetions?

-
problem:
gaming pc with ndi output enable,
streaming notebook, cant find my gaming pc in NDI Source. (source name in blank)

**Comment by pedraodeus** [comment]
The problem was the modem!
With a switch works fine!

**Comment by slavonicsniper** [comment]
Hello, I just tried NDI for the first time yesterday. First I tried it with my older laptop that is connected to my home network over the WIFI. Everything was working, my laptop could see my main PC as NDI source and add it. Then I tried the same thing with my newer laptop that is connected to my home network via etherner cable. I did everything the same as with the older laptop but my newer laptop cannot see my my PC desktop as source name in NDI when I want to add it BUT my main PC dekstop can see this laptop so I get like only one way communication. I tried to disable firewall, no success. I installed the same OBS version, same obs-ndi plugin I restarted both computers. I tried to reset my network settings. 

Any ideas what could be wrong if I can see my laptop from my main PC where I am gaming but I can't see my main PC from laptop where I'd like to stream? I don't think there is anything wrong with my main PC as I could see it as a NDI source from my older laptop that was connected over WIFI.

Thanks for help guys

I tried both suggestions but still no success. I am running out my ideas and solutions...the thing is that it worked 2 days ago on my main PC, but I had the latest windows update 1803 installed that time, yesterday I downgraded back to the previous version as I had stuttering issues after the latest WIN update. From that time my NDI plugin in OBS stopped working no laptop in my network can see it as a source in OBS. Other laptops can see each other. I tried to do clean reinstallation many times and in different ways but anyways it doesn't work...what else could I try guys? any ideas? I really want to use NDI and the saddest thing is that it was already working and now it stopped somehow...

so to recap: it was already working on my main pc where now this pc cannot be recognized by other pcs in laptop, firewall exception is set correctly everywhere

**Comment by TravisDean** [comment]
I just encountered the same issue.

MAIN-PC is what I want to send from. LAPTOP (should be) receiving.

LAPTOP can see it's own test streams, virtual inputs, and so on, but that's it.

MAIN-PC can see it's own, as well as anything LAPTOP is running simultaneously.

-----
It worked fine before I updated the laptop, probably to 1803 as it hadn't been used much.

MAIN-PC is on Insider Build 17868.

Any ideas?

Tried turning both firewalls off, restarting both. 

Interestly enough, I can get it to work with Medialook's VideoTransport technlogy.

**Comment by slavonicsniper** [comment]
Hello, try to check my issue that is resolved now here: https://github.com/Palakis/obs-ndi/issues/166#issuecomment-403022334

**Comment by dpnz** [comment]
I couldn't make sense of the solution from slavonicsniper (although I assume this is what happened to me re the IP stuff) however I managed to get a fix/workaround by uninstalling OBS and the plugin, and then reinstalling the 32Bit OBS (instead of 64bit default) and then the plugin and now I can see both sources on both computers.
