### ISSUE TITLE
FIX INSTRUCTIONS

### ISSUE THREAD

**Issue by hiromimura** [Palakis/obs-ndi#631]
_FIX INSTRUCTIONS
To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/). 

You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list. 

If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above. 

Good Luck!_

Thank you for the information. I am new to Mac and just bought Mac Mini M1. I found  libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks. But I could not find usr/local/lib for the copy. Can you please help?

Update (3/6/2021 22:28 US PST)
I found the information and use terminal to type below and works now. I installed NewTek Video Monitor before I did below.
sudo mv /usr/local/lib/libndi.4.dylib /usr/local/lib/libndi.4.dylib.bak
sudo cp /Applications/'NewTek NDI Video Monitor.app'/Contents/Frameworks/libndi.4.dylib /usr/local/lib/

Thank you
Hiroshi
_Originally posted by @mdg4486 in https://github.com/Palakis/obs-ndi/issues/590#issuecomment-757029441_

**Comment by rjhornsby** [comment]
You won't be able to see `/usr/local/lib` in the Finder because it's hidden, mostly because it's a system directory rarely used by the average user. (Could have just been a typo but the leading `/` at the beginning of `/usr/local` matters.)

I find the command approach to be much easier. However, copying files in the Finder is perfectly fine as well. Sometimes the easiest way to get a "hidden" folder to open is to literally tell the computer to open it. Open up your terminal application (Applications > Utilities > Terminal) and do

`open /usr/local/lib`

Be really careful not to mess with anything else in there. If you get `The file /usr/local/lib does not exist.`, follow the instructions below. Otherwise, you should be able to drag+copy your file now!

If you want to do the copy in the Terminal, this is how:

When you drag files from the Finder onto a terminal window, it automatically puts their location for you. 
 Open up your terminal application (Applications > Utilities > Terminal) and do the following commands:

```
mkdir -p /usr/local/lib
cp <drag your libndi.4.dylib onto your terminal window> /usr/local/lib/
```

`mkdir` creates the directory if it's missing
`cp` is short for 'copy'

As I noted in the other thread, copying it didn't work for me for some reason. I had to create a link or "alias". If you run into the same issue I did, you can (in the Terminal) do this:

```
ln -s <drag your libndi.4.dylib onto your terminal window> /usr/local/lib/libndi.4.dylib
```

`ln` means create a link to the target (/Applications...) at the location `/usr/local/lib/libndi.4.dylib`

**Comment by hiromimura** [comment]
> You won't be able to see `/usr/local/lib` in the Finder because it's hidden, mostly because it's a system directory rarely used by the average user. (Could have just been a typo but the leading `/` at the beginning of `/usr/local` matters.)
> 
> I find the command approach to be much easier. However, copying files in the Finder is perfectly fine as well. Sometimes the easiest way to get a "hidden" folder to open is to literally tell the computer to open it. Open up your terminal application (Applications > Utilities > Terminal) and do
> 
> `open /usr/local/lib`
> 
> Be really careful not to mess with anything else in there. If you get `The file /usr/local/lib does not exist.`, follow the instructions below. Otherwise, you should be able to drag+copy your file now!
> 
> If you want to do the copy in the Terminal, this is how:
> 
> When you drag files from the Finder onto a terminal window, it automatically puts their location for you.
> Open up your terminal application (Applications > Utilities > Terminal) and do the following commands:
> 
> ```
> mkdir -p /usr/local/lib
> cp <drag your libndi.4.dylib onto your terminal window> /usr/local/lib/
> ```
> 
> `mkdir` creates the directory if it's missing
> `cp` is short for 'copy'
> 
> As I noted in the other thread, copying it didn't work for me for some reason. I had to create a link or "alias". If you run into the same issue I did, you can (in the Terminal) do this:
> 
> ```
> ln -s <drag your libndi.4.dylib onto your terminal window> /usr/local/lib/libndi.4.dylib
> ```
> 
> `ln` means create a link to the target (/Applications...) at the location `/usr/local/lib/libndi.4.dylib`

I appreciate your detailed response. I experienced terminal command with Windows before, but not with Mac. I will carefully try it. If there is a tool like Explorer, it would be much easier. Anyway, I will try it later and pet you know the result.
Thanks again.

**Comment by hiromimura** [comment]
Update (3/6/2021 22:28 US PST)
I found the information and use terminal to type below and works now. I installed NewTek Video Monitor before I did below.
sudo mv /usr/local/lib/libndi.4.dylib /usr/local/lib/libndi.4.dylib.bak
sudo cp /Applications/'NewTek NDI Video Monitor.app'/Contents/Frameworks/libndi.4.dylib /usr/local/lib/

Thank you so much for the help.
Hiroshi
