### ISSUE TITLE
Raspberry Pi Support?

### ISSUE THREAD

**Issue by mobilegmYT** [Palakis/obs-ndi#640]
1. OBS Studio runs, you can install it from the pi-apps application.
2. You can use `MESA_GL_VERSION_OVERRIDE=3.2` env for opengl 3.2
3. This project seems to be a open-source version of libndi and supports pi 4: https://www.reddit.com/r/VIDEOENGINEERING/comments/hbifrh/open_source_ndi_library/fvb3fmr?utm_source=share&utm_medium=web2x&context=3

**Comment by tt2468** [comment]
NDI 5 supports ARM now. This means that it will likely be possible to build obs-ndi version 5.0.0 for raspberry pi. However, we have no intentions of providing any official releases for the platform.

**Comment by shodanx2** [comment]
Hello,
I understand this is closed but this is for people who will try to build obs-ndi for RPiOS anyway.

My particular reason for compiling obs-ndi on RPiOS is not for using with OBS but for this NDI plugin for gstreamer
https://github.com/teltek/gst-plugin-ndi

This plugin requires libndi and they point to this project, obs-ndi as a source to compile libndi
They point to this file https://github.com/Palakis/obs-ndi/releases/download/4.5.2/libndi3_3.5.1-1_amd64.deb

So I am trying to build libndi from obs-ndi source code but for my arch

I have tried it and failed, here is how far I have gotten

First I got both source trees of obs and obs-ndi

```
git clone https://github.com/obsproject/obs-studio
git clone https://github.com/Palakis/obs-ndi.git
```

Next I installed cmake 

`sudo apt install -y cmake `

On the obs-ndi home page section 
`cmake -DLIBOBS_INCLUDE_DIR="<path to the libobs sub-folder in obs-studio's source code>" -DCMAKE_INSTALL_PREFIX=/usr ..`

So in my case, it fails as follows

```
pi@leftscreen:~/obs-ndi $ cmake -DLIBOBS_INCLUDE_DIR=../obs-studio/libobs/ -DCMAKE_INSTALL_PREFIX=/usr ..
CMake Error: The source directory "/home/pi" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

The problem is the ..   at the end of the line, should be ./

Gives the following output which fails on finding libobs unfortunately 

```
pi@leftscreen:~/obs-ndi $ cmake -DLIBOBS_INCLUDE_DIR=../obs-studio/libobs/ -DCMAKE_INSTALL_PREFIX=/usr ./
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/pi/obs-ndi/CMakeFiles/CMakeOutput.log".
```


The file CMakeOutput.log is kind of big so I will paste it to pastebin rather than here
https://pastebin.com/bHWKPPQn


As you can see it request a file called libobs-config.cmake, I searched my entire system for this file but it's not there

```
pi@leftscreen:~/obs-ndi $ sudo find / | grep -i libobs-config.cmake
find: ‘/run/user/1000/gvfs’: Permission denied
pi@leftscreen:~/obs-ndi $
```

**Comment by tt2468** [comment]
LibNDI is just the NDI redistributables packaged as a Deb. If you want to create one for Arch, you'd have to download the NDI SDK for linux and package the binaries with whatever package manager Arch uses.

**Comment by shodanx2** [comment]
By "arch" I mean cpu architecture ARMv7, I've done all of this on Raspberry Pi OS "bullseye" release
