### ISSUE TITLE
OBS-NDI using over 50% CPU without even enabling NDI output on gaming pc

### ISSUE THREAD

**Issue by Korgeli** [Palakis/obs-ndi#79]
My OBS is using already 50-55% of CPU and GPU 15-20% on gaming pc even though NDI isn't even enabled yet and OBS has just a black screen. I was reading ppls opinions with similar setups and didn't see anyone having such huge numbers without even having any other programs on the background. In case I enable NDI, CPU usage goes up to 68%. Bug or settings off? If I start OBS without NDI, it's at 5-8% load, so launching OBS with NDI takes already 50% of CPU load at idle.

Tried with 1920x1080 or 1280x720. 1080p had 2-5% more load. Filter was on Lanczos and fps on 60. Lowering to 30fps lowered CPU usage by 5% - 8%. Noticed also that 32bit uses 2-5% less CPU and process priority as high uses 2-5% more CPU aswell. CPU is still really close to 60% load on gaming pc and I don't even have the game itself on.

i7 4770K
16GB 2133 ddr3
GTX 780
Windows 10 64bit

**Comment by Helgaiden** [comment]
You should post OBS log info, there really isnt alot to go on. I'd also try uninstalling NDI, running ccleaner and doing a ccleaner registry cleanup, rebooting, and trying again. If you have any Browser Sources, or any sources at all, across multiple scenes, id go through each source in each scene and look for a checkbox that says "shut down source when not in use" and click that box. Ran into a high CPU usage scenario once when trying NDI out, and it turned out to be the 4-5 animated browser sources across multiple scenes using it all up. They'd still run even if you werent on them, so that checkbox is imperative to help with that.

**Comment by Korgeli** [comment]
Damn... I had few browser sources from Streamelements that was left unchecked. Tried to look up for the solution from forums and few YT video comments but couldn't find anyone having this issue. CPU usage went down to 30% now and seems pretty good. Thanks for the help!
