### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by HumanG33k** [Palakis/obs-ndi#796]
It's my first try of the ndi plugin. 

I follow the install on my debian testing 
(dpkg -i packages)

But when i start obs after the ndi-obs. it crash (not start).
The command line output  is : 
```
debug: Found portal inhibitor
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/fr-FR.ini
Attempted path: /usr/share/obs/obs-studio/locale/fr-FR.ini
info: Using preferred locale 'fr-FR'
Attempted path: share/obs/obs-studio/themes/Yami.qss
Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
info: CPU Speed: 3292.751MHz
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 15949MB Total, 6508MB Free
info: Kernel Version: Linux 6.0.0-2-amd64
info: Distribution: "Debian GNU/Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 5.15.6 (runtime), 5.15.4 (compiled)
info: Portable mode: false
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 28.0.1.11-3 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
        max buffering:   960 milliseconds
        buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD CEDAR (DRM 2.50.0 / 6.0.0-2-amd64, LLVM 15.0.5)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 22.2.4, shading language 3.30
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1280x720
        downscale filter:  Bicubic
        fps:               60/1
        format:            NV12
        YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
        name: Par défaut
        id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] No captures available
info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.10.0)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 00:05:02 Apr  1 2020 4.5.1)
QWidget: Must construct a QApplication before a QWidget
Abandon
```

If i miss something let me know. 
What information de you need ?

**Comment by Uro1** [comment]
I have had this same error occur slightly further on in the log on a fresh install of OBS Studio - 29.0.2.1-1+b1 (linux) on Debian Bookworm installed via apt package manager with obs-ndi 4.11.1 installed from this GitHub repo (deps are installed: libndi5/libndi5-dev + NDI SDK runtime, as per install instructions).

I have no scenes set up and the only non-default OBS plugin is obs-ndi.
```
info: [obs-ndi] obs_module_load: hello ! (version 4.11.1)  
info: [obs-ndi] load_ndilib: Trying '/usr/lib/libndi.so.5'  
info: [obs-ndi] load_ndilib: Found NDI library at '/usr/lib/libndi.so.5'  
info: [obs-ndi] load_ndilib: NDI runtime loaded successfully  
info: [obs-ndi] load_ndilib: NDIlib_v5_load found  
info: [obs-ndi] obs_module_load: NDI library initialized successfully (NDI SDK LINUX 09:57:02 Feb  2 2023 5.5.3)  
debug: output 'NDI Main Output' (ndi_output) created  
debug: output 'NDI Preview Output' (ndi_output) created  
QWidget: Must construct a QApplication before a QWidget  
Aborted  
  
$ obs -V
OBS Studio - 29.0.2.1-1+b1 (linux)
$ uname -a
Linux Vanaheimr 6.1.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1 (2023-03-05) x86_64 GNU/Linux
$ qmake --version
QMake version 3.1
Using Qt version 5.15.8 in /usr/lib/x86_64-linux-gnu
$ qmake6 --version
QMake version 3.1
Using Qt version 6.4.2 in /usr/lib/x86_64-linux-gnu
```

This prevents obs-studio from starting, removal of the obs-ndi package (`apt remove obs-ndi -y`) returns obs-studio to normal functionality.

The error will only be recorded by running `obs --verbose`, the standard/non-verbose log file does not record the error.   

I have attached a copy of my complete console output from running `obs --verbose` with system version info including installed Qt versions at the end of the file.

[obs-console.txt](https://github.com/obs-ndi/obs-ndi/files/11011750/obs-console.txt)

Is there any more information you require? 
I'd be happy to test fixes for this issue as it's a blocker on me using obs-ndi at the moment.

**Comment by Uro1** [comment]
I have now built obs-studio and obs-ndi both from source, and I am still getting the same error as reported above, if I remove the obs-ndi plugin then obs runs as expected.

any ideas as to what may be causing this @paulpv ?

**Comment by Uro1** [comment]
For anyone else who comes across this issue on Debian Bookworm, the `obs-studio` version available through the Debian PPA's at the time of writing is not compatible with `obs-ndi` as it is build wqith Qt5, you will have to compile and install your own version using the steps below:

+  I had to completely remove & purge Qt5 from my system with apt:
```
sudo apt remove qtbase5-dev qtbase5-private-dev libqt5svg5-dev qtwayland5 -y \  
&& sudo apt purge qtbase5-dev qtbase5-private-dev libqt5svg5-dev qtwayland5 -y \  
&& sudo apt autoclean
```
+  Install Qt6 (I already had these installed): 
`sudo apt install qt6-base-dev qt6-base-private-dev libqt6svg6-dev qt6-wayland`

+  Clone the [obs-studio](https://github.com/obsproject/obs-studio) repo.

+ Install all of the `obs-studio` dependencies **_except the Qt5 dependencies_**. 
[https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#2-get-the-dependencies](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#2-get-the-dependencies)

+ Compile `obs-studio` from source with the `-DQT_VERSION=6` cmake flag in step 3 of the `obs-studio` linux build instructions - [https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux)

+ Skip step 6 as it is unnecessary as we use apt to manage packages.
[https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#6-install-the-project](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#6-install-the-project)

+ Run Step 7  [https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#7-create-debian-package](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#7-create-debian-package)

+ Followed by `sudo apt install ./build/obs-studio-29.0.2-*-Linux.deb` (adjust this for the filename of the deb produced from the step above)

+ Additionally you will want to put a hold on apt updating obs-studio from the debian PPA's as it will "upgrade" your compiled version with the PPA version, which as of writing is a version that does not work with obs-ndi due to being compiled with Qt5:
`sudo apt-mark hold obs-studio`
Should you want to unhold the package, i.e. if a new version is released and you create a new build of obs-studio, you can simply enter the following to unhold the package, install/upgrade it to your new deb file and reapply the hold as above:
`sudo apt-mark unhold obs-studio`

N.B. You will have to empty your `build/` directory inside your copy of the `obs-studio` repo in order to build successfully if you attempted a build while having Qt5/Qt5libraries installed, as running `cmake --build YOUR_BUILD_DIRECTORY -t clean` does not clean the remnants of Qt5 from your previous build files or cmakefiles.
