### ISSUE TITLE
Add New (5.5.2.0) NDI Runtime in FTP repo

### ISSUE THREAD

**Issue by Trouffman** [Palakis/obs-ndi#810]
There is a new version of the NDI Runtime available : 5.5.2.0
Get it from the SDK.

Windows Users : 

Get the latest version of the NDI Runtime at : http://new.tk/NDIRedistV5

**Comment by Trouffman** [comment]
Tested and havent encountrered any issue so far with it (except an Audio saturation issue but seems unrelated to the runtime version)

**Comment by Trouffman** [comment]
Confirmed that the Audio issue is not fromt he runtime but a bug in the code that is solved in one of the fork.

**Comment by Trouffman** [comment]
This is the Official Link to DL the latest Windows Runtime from NDI /Newtek : http://new.tk/NDIRedistV5

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
The Linux NDI runtimes can be found there.
The Windows and MacOS runtimes can be downloaded from http://new.tk/NDIRedistV5 and http://new.tk/NDIRedistV5Apple respectively.

I have no plans to maintain Palakis' FTP folder.

**Comment by Jaxel** [comment]
[http://new.tk](http://new.tk/NDIRedistV5) appears to be dead...

**Comment by paulpv** [comment]
It does indeed look down.
It worked yesterday.

**Comment by paulpv** [comment]
24 hours later, still not working.
I have posted to:
https://forums.newtek.com/threads/http-new-tk-seems-down-and-thus-http-new-tk-ndiredistv5-http-new-tk-ndiredistv5apple.167380/

**Comment by Trouffman** [comment]
Closing as it is better to link back to the source than re-hosting. (purpose of this issue)
See the discussion for more info : #831
