### ISSUE TITLE
Audio quality poor over regular NDI Source

### ISSUE THREAD

**Issue by zachflauaus** [Palakis/obs-ndi#83]
- OBS 20.1.3 on source and destination PC
- Windows 10, Creators Update on both PCs
- OBS-NDI Version 4.2 on both PCs
- Highest bandwidth options set on destination PC

Running OBS-NDI version 4.2, OBS 20.1.3, Windows 10 Creators Update on both machines

I think after 4.2 was released, the audio quality in the regular NDI Source (no dedicated audio filter on source PC) tanked, sounding like a poorly compressed audio file. After I inserted the dedicated audio filter on the source PC, the audio sounds as it should instead. I'm wondering if the bandwidth options introduced with 4.2 have something to do with this. I'd be glad to provide video samples.

**Comment by Palakis** [comment]
@zachflauaus Hmm, strange. Make sure the receiving source is using High Bandwidth mode.
In the NDI SDK, this is the only control I can think of that could alter audio quality.

**Comment by Abaddonix** [comment]
Hey @Palakis sorry for opening this back up but I have searched all over google, forums, reddit, and here to find a solution. I was streaming about a month ago using NDI plugin for OBS Studio, everything worked great! Audio quality was great, and so was video. I took a month break and came back last night to stream and for some reason my audio is incredibly choppy / distorted.

I've tried all sorts of fixes, I've installed the latest versions of NDI plugin, as well as OBS to no avail. The audio monitoring sounds perfect on the stream PC (destination PC), I have the highest bandwidth setup on this as well. Nothing has changed on my setup since I last streamed, just can't seem to figure out what the deal is.

Both PCs are connected via 1gb ethernet, the quality of audio is terrible for both recording and streaming.

Thanks in advance for any help you could provide, and thanks so much for creating this plugin! It's seriously been amazing using it up until this point.

**Comment by Rednose58** [comment]
I have the same issue.  I asked the question in the OBS Forum.  Here is a link to it. [https://obsproject.com/forum/search/3427249/](url)
