### ISSUE TITLE
Unstable Frame Times Under Heavy Load.

### ISSUE THREAD

**Issue by PixelTwitch** [Palakis/obs-ndi#94]
During graphically intense areas in games, the NDI output appears to have inconsistant frame times resulting in OBS on the streaming computer to appear very stuttery. The reason I am confident its not just a OBS limitation (on the gaming computer) is because using software like NDI Studio Monitor, the NDI stream appears to be much smoother than that displayed in OBS. Surprisingly NDI Transmit suffers in the same way your NDI input does. Bringing NDI Transmit into OBS shows only a smalll improvement in video smoothness when compared to OBS NDI Input. However, using NDI Studio Monitor on a second screen and then screen capping that second screen can pull in the exact same feed quality but much smoother. 

This leads me to believe that NDI Studio Monitor "buffers" or smooths out the frame times in some way.

**Comment by Palakis** [comment]
By "very stuttery", how much is it? 45fps? 30fps? 15fps?
Can you also please try using the source in "Sync: External" mode?

**Comment by Palakis** [comment]
"Sync: External" being a setting in the NDI source in OBS.

**Comment by PixelTwitch** [comment]
Hello @Palakis 

Please check out the YouTube video below. This is OBS NDI vs NewTek NDI Studio Monitor (video is unlisted). This video is only short and shows Network (guessing thats what you mean when you say external sync) Sync with both Hardware Accel on and off...

https://www.youtube.com/watch?v=liU7GzNqWEs

Performance is about the same with or without streaming and with or without NewTek Studio Monitor running (basically cannot notice any visible difference). From time to time OBS does become smooth and when it does it is VERY SMOOTH not only 60fps but well paced 60fps that is as smooth as silk. 

This happens on all systems in multiple network configs (including crossover cables). 
Systems inc,

i9 7900x + 1080ti + 64GB ram
i7 3930k + RX580 + 32GB ram
Ryzen 1700 + GTX980 + 8GB ram

While different, I am able to push out smooth RTMP on all systems and while the bandwidth is not as high on RTMP, I believe that the smooth studio monitor shows this is not a bandwidth problem.

**Comment by PixelTwitch** [comment]
@Palakis I was wondering if there is anything else you could think I should try in terms of testing. I would love to be using NDI rather than RTMP just still really struggling when it comes to smoothness.

**Comment by PatTheMav** [comment]
Can confirm the behavior @PixelTwitch reports, I actually did the same side-by-side "analysis" he uploaded to YouTube and found the Studio Monitor output to always have a more consistent and stable frame rate (and given that there are what I perceive as "pockets" of fluidity I expect frame times to be the bigger issue than the actual rate of frames).

It's really noticeable in the demo when he swirls the camera around (effectively creating lots of motion vector changes), which also hints towards "scene complexity" (The Witcher 3 is hit by this hard due to all its moving foliage/trees).

@Palakis these issues might/do cover the same issue, so maybe mark them as duplicates:

- https://github.com/Palakis/obs-ndi/issues/84
- https://github.com/Palakis/obs-ndi/issues/87
- https://github.com/Palakis/obs-ndi/issues/100

Is there anything we can do for you with regards to debug output/reporting?

**Comment by rgbjoy** [comment]
Yes! I thought I was going crazy... I can always tell when something isn't true 60FPS and I kept looking over at my streaming OBS and noticing not true 60FPS. Is there any solutions around this?

**Comment by sorenhoyer** [comment]
I can confirm this issue as well. Was also driving me crazy. Thanks for the workaround of capturing studio monitor output

**Comment by Helgaiden** [comment]
Idk I think it's pretty smooth to me, what do you guys think? Not true 60fps? This is the last stream I did with fresh updated OBS NDI installations. Stream PC is a Xeon x5650 6 core/12 thread at 4ghz with OBS output at 1280x720p60, Lanczos filter, 4500kbps bitrate, medium CPU preset. 

http://www.twitch.tv/coalitiongamingcrew/v/224821028?sr=a&t=199s

**Comment by PatTheMav** [comment]
@Helgaiden The stream itself is kinda choppy at times (especially at team fights and more "sweeping" motion), but that could also be down to encoder overload. Thus it's more important to compare OBS output with NDI Studio Monitor output to check for this issue.

**Comment by PixelTwitch** [comment]
Its looking good enough for twitch @Helgaiden but its certainly still not consistent. due to how quick the stutters are I am not confident that this is actually an encode issue and is likely the same issue we have with NDI just maybe not quite as bad.

**Comment by sorenhoyer** [comment]
It doesn't look like smooth 60fps to me - sure sometimes, but that's the whole problem. It's "Unstable Frame Times Under Heavy Load" as the title says. :)

**Comment by PatTheMav** [comment]
I've been scouring the OBS forums for some other issues recently and found a hint about making sure to set the output frame rate to an integer value (and not to a "common" frame rate) and set it to "60" then (the "common" frame rate would be 59.94 otherwise).

I haven't had the chance to do a proper A/B test, but maybe some of you can check if this helps in evening out the pacing of frames.

**Comment by gr8in83** [comment]
Doesnt

**Comment by Helgaiden** [comment]
I changed my capture method for last night's stream. I set OBS to capture the NDI tools Monitor window to stream that. I couldn't quite get it to fit my 1280x720 base canvas though, something about how it was capturing the monitor window i guess. I still do see some stutter, but im thinking that was the game because of its own issues still. My gaming PC hangs around 60fps up to 80fps when OBS is open sending the NDI feed, with somewhat big frame drops because of PUBG crappy optimization. OBS using 7-10% CPU on its own, PUBG is super sensitive to that. I have my overlays and such all set up on my gaming PC so thats adding the CPU utilization. When i dont have OBS open, i can easily hang around 80-120fps. 

I have a 6-core/12-thread Xeon E5-1650v2 on the way that i will be putting in an Asus p9x79e-ws motherboard and transplanting into my main rig, so this should help out big time.

Anyways, heres last night's NDI Monitor-captured stream. When its smooth, it does indeed look smoother to me but im not convinced of the visual quality itself at the moment. Seems like its losing some compared to OBS capturing it directly. But for the smoothness it brings, its not a bad tradeoff. Low bandwidth mode was not enabled.

https://www.twitch.tv/videos/234258609

**Comment by violentbunny** [comment]
I am outputting the video feed from obs using NDI and receiving it with NDI Studio monitor which is present in NDI tools.
The video feed if directly taken in obs in streaming PC creates stutters for me so I captured the NDI source monitor window in OBS in the streaming PC and stream it from there.

**Comment by Naruske** [comment]
Just giving a heads up I am too having this problem.

**Comment by PatTheMav** [comment]
@violentbunny Unfortunately that seems to be a workaround for windows only - getting the NDI Monitor output captured and properly sized on macOS is a pain and frame times where even more over the place then.

**Comment by Maelas84** [comment]
I am having this same issue as well. Stream looks great but is not 60 fps for sure with many micro stuttering going on. I will try the ideas from this thread and report back if it will help the investigation.
